server:
  port: 25678

mongodb:
  encrypted-uri: "{cipher}4c2437e12cbac1fef39e51d77da52ea9dd382f1c1c649d9789d66fac09e4e1c2ce4c6ee79d334720467789bac81caabae5fc9ebf82212192687bd30a70960f54aa467e6512e1d25943b7b6561914d10d4f3cf8a8c3eb410652bfa0e7490267f0"
  base: "/notification_db?replicaSet=rs0&authSource=admin" 
  
spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: "${mongodb.encrypted-uri}${mongodb.base}"
      auto-index-creation: true

  kafka:
    bootstrap-servers: kafka-primary:19092, kafka-secondary:19092, kafka-backup:19092

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8516/eureka/
api:
  member-read-service:
    url: "http://member-read-service:27671/v1"
  comment-service:
    url: "http://comment-service:25673/v1"
  feed-read-service:
    url: "http://feed-read-service:27670/v1"
  shorts-read-service:
    url: "http://shorts-read-service:27679/v1"
